"""Investment-theme label taxonomy and keyword rules."""

LABELS = [
    "Demand / Revenue Growth",
    "Margins / Profitability",
    "Regulation / Legal",
    "Capital Allocation / CAPEX",
    "Product / Technology Strategy",
    "Macro / Cyclical Risk",
    "Neutral / Other",
]

WEAK_LABEL_KEYWORDS = {
    "Demand / Revenue Growth": [
        "customer demand",
        "strong demand",
        "end-market demand",
        "demand recovery",
        "demand environment",
        "revenue growth",
        "sales growth",
        "net sales increased",
        "net revenue increased",
        "increase in revenue",
        "increase in sales",
        "higher revenue",
        "higher sales",
        "bookings",
        "backlog",
        "order growth",
        "customer adoption",
        "market adoption",
        "market opportunity",
        "market expansion",
        "secular growth",
        "tailwinds",
        "new customers",
        "design wins",
        "unit growth",
        "volume growth",
        "market share",
        "share gain",
        "share gains",
        "customer wins",
        "pipeline",
        "end-market recovery",
    ],

    "Margins / Profitability": [
        "gross margin",
        "operating margin",
        "margin pressure",
        "margin expansion",
        "margin improvement",
        "margin decline",
        "pricing pressure",
        "price erosion",
        "average selling price",
        "asp",
        "cost pressure",
        "higher costs",
        "lower costs",
        "input costs",
        "supply chain costs",
        "manufacturing costs",
        "cost of goods sold",
        "cost of revenue",
        "product mix",
        "favorable mix",
        "unfavorable mix",
        "profitability",
        "gross profit",
        "operating profit",
        "operating income",
        "net income",
        "earnings per share",
        "eps",
        "ebitda",
        "operating leverage",
        "cost reduction",
        "cost savings",
        "expense reduction",
        "efficiency improvements",
        "free cash flow",
    ],

    "Regulation / Legal": [
        "regulation",
        "regulatory",
        "legal",
        "lawsuit",
        "litigation",
        "claim",
        "claims",
        "investigation",
        "compliance",
        "non-compliance",
        "export control",
        "export controls",
        "trade restrictions",
        "sanctions",
        "government restrictions",
        "government regulation",
        "antitrust",
        "intellectual property",
        "patent",
        "patent infringement",
        "data privacy",
        "privacy law",
        "tax law",
        "tariff",
        "tariffs",
        "customs",
        "environmental regulations",
        "securities laws",
    ],

    "Capital Allocation / CAPEX": [
        "capital allocation",
        "capital expenditures",
        "capex",
        "capital investment",
        "investment in capacity",
        "capacity expansion",
        "capacity investments",
        "data center investment",
        "fab investment",
        "manufacturing capacity",
        "equipment purchases",
        "infrastructure investment",
        "facility expansion",
        "construction",
        "research and development",
        "r&d",
        "technology investment",
        "share repurchase",
        "repurchase program",
        "buyback",
        "dividend",
        "debt repayment",
        "debt reduction",
        "acquisition",
        "merger",
        "m&a",
        "strategic investment",
        "liquidity",
        "cash equivalents",
        "balance sheet",
        "capital resources",
    ],

    "Product / Technology Strategy": [
        "artificial intelligence",
        "generative ai",
        "machine learning",
        "accelerated computing",
        "gpu",
        "accelerator",
        "data center",
        "cloud",
        "cloud infrastructure",
        "product roadmap",
        "roadmap",
        "platform",
        "architecture",
        "product launch",
        "new product",
        "new products",
        "innovation",
        "inference",
        "training workloads",
        "neural network",
        "large language model",
        "llm",
        "ai infrastructure",
        "custom silicon",
        "in-house chips",
        "customer-developed chips",
        "alternative solutions",
        "technology transition",
        "node transition",
        "process technology",
        "hbm",
        "high bandwidth memory",
        "ddr5",
        "memory technology",
        "networking",
        "optical",
        "ethernet",
        "switching",
        "storage",
        "ssd",
        "compute",
        "semiconductor solutions",
    ],

    "Macro / Cyclical Risk": [
        "macroeconomic",
        "macro",
        "recession",
        "economic slowdown",
        "slowdown",
        "inflation",
        "interest rates",
        "foreign exchange",
        "fx",
        "currency",
        "currency fluctuations",
        "geopolitical",
        "china",
        "economic uncertainty",
        "market uncertainty",
        "consumer spending",
        "enterprise spending",
        "cloud spending",
        "semiconductor cycle",
        "cyclical",
        "cyclicality",
        "inventory correction",
        "inventory adjustments",
        "customer inventory",
        "downturn",
        "upturn",
        "supply constraints",
        "supply shortage",
        "supply-demand imbalance",
        "industry conditions",
        "market conditions",
        "global economy",
    ],

    "Neutral / Other": [],
}