"""Investment-theme label taxonomy and keyword rules."""

LABELS = [
    "Demand Growth",
    "Margins / Profitability",
    "Competition",
    "Regulation / Legal",
    "Capital Allocation / CAPEX",
    "AI / Product Strategy",
    "Macro Risk",
    "Neutral / Other",
]

WEAK_LABEL_KEYWORDS = {
    "Demand Growth": [
        "demand",
        "customer demand",
        "strong demand",
        "end-market demand",
        "growth",
        "revenue growth",
        "sales growth",
        "bookings",
        "backlog",
        "order growth",
        "customer adoption",
        "adoption",
        "market opportunity",
        "market expansion",
        "secular growth",
        "tailwinds",
        "new customers",
        "design wins",
        "unit growth",
    ],
    "Margins / Profitability": [
        "margin",
        "gross margin",
        "operating margin",
        "margin pressure",
        "pricing pressure",
        "price erosion",
        "cost pressure",
        "higher costs",
        "input costs",
        "supply chain costs",
        "product mix",
        "profitability",
        "net income",
        "operating income",
        "gross profit",
        "operating profit",
        "earnings",
        "eps",
        "ebitda",
        "operating leverage",
        "cost reduction",
        "cost savings",
        "free cash flow",
    ],
    "Competition": [
        "competition",
        "competitive",
        "competitor",
        "competitors",
        "compete",
        "market share",
        "share loss",
        "pricing competition",
        "competitive pressure",
        "substitute products",
        "alternative solutions",
        "new entrants",
        "custom silicon",
        "in-house chips",
        "customer-developed chips",
        "rival",
    ],
    "Regulation / Legal": [
        "regulation",
        "regulatory",
        "legal",
        "lawsuit",
        "litigation",
        "claim",
        "investigation",
        "compliance",
        "export control",
        "export controls",
        "trade restrictions",
        "sanctions",
        "government restrictions",
        "antitrust",
        "intellectual property",
        "patent",
        "data privacy",
        "tax law",
        "tariff",
    ],
    "Capital Allocation / CAPEX": [
        "capital allocation",
        "capital expenditures",
        "capex",
        "capital investment",
        "investment in capacity",
        "capacity expansion",
        "data center investment",
        "fab investment",
        "manufacturing capacity",
        "equipment purchases",
        "infrastructure investment",
        "facility expansion",
        "construction",
        "research and development",
        "r&d",
        "technology investment",
        "share repurchase",
        "repurchase program",
        "buyback",
        "dividend",
        "debt repayment",
        "acquisition",
        "merger",
        "m&a",
        "liquidity",
        "balance sheet",
    ],
    "AI / Product Strategy": [
        "artificial intelligence",
        " ai ",
        "generative ai",
        "machine learning",
        "accelerated computing",
        "gpu",
        "accelerator",
        "data center",
        "cloud",
        "product roadmap",
        "roadmap",
        "platform",
        "architecture",
        "product launch",
        "new product",
        "innovation",
        "inference",
        "training workloads",
        "neural network",
        "large language model",
        "llm",
        "ai infrastructure",
    ],
    "Macro Risk": [
        "macroeconomic",
        "macro",
        "recession",
        "slowdown",
        "inflation",
        "interest rates",
        "foreign exchange",
        "fx",
        "currency",
        "geopolitical",
        "china",
        "tariff",
        "supply constraints",
        "supply shortage",
        "economic uncertainty",
        "consumer spending",
        "enterprise spending",
        "semiconductor cycle",
        "cyclical",
    ],
    "Neutral / Other": [],
}

